### ISSUE TITLE
Screen sharing error: Capture process not started

### ISSUE THREAD

**Issue by Philippe734** [dwservice/agent#55]
Since November, the screen sharing don't works anymore.

I can use any of function of dservice, as shell or monitor, except the screen sharing. There is the following error, when the host device is running dwservice (without install):

![c](https://user-images.githubusercontent.com/24923693/99185188-89ebe980-2748-11eb-8569-a887cb05518f.png)

Same error on the following tested system:
Host device (the one to be remote-controlled):
Ubuntu 20.04
Xubuntu 20.04
Linux Mint 19.3
Bodhi linux 5.0
Client device (the one, that remote-controls the host device):
Firefox and Chromium:
Xubuntu 20.04
Linux Mint 19.3

**Comment by JonnyTech** [comment]
Do you have any blocks, ie firewall, sandbox, etc? No problems here with multiple Linux hosts and guests.

**Comment by Philippe734** [comment]
Yes I already checked. Firewall disabled on each host and guest. I tested on two different routers (internet access point). I can use all function of dwservice as shell and monitor, but the not screen sharing. When the screen sharing try to start, I got the error: `Process not started`. Here the log from the terminal when I try to start screen sharing:
```
mint@mint:~$ '/home/mint/Downloads/dwagent.sh'
Extracting file ...
Running installer ...
Traceback (most recent call last):
  File "/home/webdel/Sviluppo/dwsgit/agent/core/agent.py", line 7, in <module>
  File "/home/webdel/Sviluppo/dwsgit/agent/core/communication.py", line 9, in <module>
  File "/root/pycompile/runtime64/lib/python2.7/ssl.py", line 97, in <module>
ImportError: /tmp/dwagent_install20201115172213/runtime/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: PyUnicodeUCS2_AsEncodedString
Traceback (most recent call last):
  File "/home/webdel/Sviluppo/dwsgit/agent/core/agent.py", line 7, in <module>
  File "/home/webdel/Sviluppo/dwsgit/agent/core/communication.py", line 9, in <module>
  File "/root/pycompile/runtime64/lib/python2.7/ssl.py", line 97, in <module>
ImportError: /tmp/dwagent_install20201115172213/runtime/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: PyUnicodeUCS2_AsEncodedString
Traceback (most recent call last):
  File "/home/webdel/Sviluppo/dwsgit/agent/core/agent.py", line 7, in <module>
  File "/home/webdel/Sviluppo/dwsgit/agent/core/communication.py", line 9, in <module>
  File "/root/pycompile/runtime64/lib/python2.7/ssl.py", line 97, in <module>
ImportError: /tmp/dwagent_install20201115172213/runtime/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: PyUnicodeUCS2_AsEncodedString

```

**Comment by miranius** [comment]
same issue with connection to Ubuntu 18.04. Nothing has changed in settings: came after the weekend.

**Comment by vmdude** [comment]
Same issue with MacOS agent from a few days back.

**Comment by Philippe734** [comment]
Same issue with Windows 10 Hiren iso live on both host and guest. Definitely, the problem come from dwservice, not router, nor OS. Now, I don't trust you JonnyTech ;-p
Windows 10 Hiren iso live: https://www.hirensbootcd.org/

**Comment by JonnyTech** [comment]
> Now, I don't trust you JonnyTech ;-p

It's OK, let's see what is different:

> when the host device is running dwservice (without install)

On my systems I have installed DWService. How exactly are you running it?

**Comment by Philippe734** [comment]
I'm running the agent without install, just executed. Please, download any ISO live, boot on host and guest and test the screen sharing with the agent not installed.

**Comment by Coeur-Noir** [comment]
Hi,

same issue here ( no screen sharing ) from a Xubuntu 18.04 but ok from Win10 machines.

dwagent is in the list of process, as root, on the remote Xub.
I can also see there that the graphical session is launched for the expected user.

**Comment by qskousen** [comment]
I have the same issue (can't use screen). Whenever I try, system log says:
```
kernel: dwagent[8494]: segfault at 3930 ip 0000000000003930 sp 00007ffffebceba8 error 14 in dwagent[400000+1000]
```

**Comment by victoramdz** [comment]
Hi, 
Same issue here in both cases, (installed and executed). Ubuntu mate 18.04  clients.

**Comment by notAro14** [comment]
Hello,

I have the same problem as well. I'm on Ubuntu 20.04

` /tmp/dwagent_install20201117101721/runtime/bin/dwagent: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory`

**Comment by dwservice** [comment]
Hello, we have introduced a bug with last update, We are working to fix it.

**Comment by dwservice** [comment]
I have published an update. Could you give me a feedback.

**Comment by Philippe734** [comment]
> I have published an update. Could you give me a feedback.

It works fine, fixed quickly, thank you! I tested the following systems:
Xubuntu 20.04 host + guest on firefox on Ubuntu 20.04
Ubuntu 20.04 host + guest on firefox Ubuntu Mate 20.04
Windows 10 Hiren live host + guest on firefox Ubuntu Mate 20.04

**Comment by qskousen** [comment]
I still have the same issue I described [here](https://github.com/dwservice/agent/issues/55#issuecomment-728366873), regardless of using the installed version or running a downloaded version. Do I have a different issue? I assumed it was the same one because it started at the same time and led to the same issue of the screen now working but perhaps I was mistaken, as I do have a different error message.

**Comment by Coeur-Noir** [comment]
Not yet here.

Anything to do for updating or restarting dwagent on _×buntu_ 18.04 ?

**Comment by dwservice** [comment]
I have installed these virtual machine Ubuntu 18.04, Xubuntu 18.04 and screen works fine. Maybe there was a problem on agent update. Can you reinstall it?

**Comment by victoramdz** [comment]
Hi, I wonder if the upgrade agent is unattended or need it to reboot.

**Comment by Coeur-Noir** [comment]
My guess, I should uninstall first ?

Is it something like : 
```
/home/My/Path/To/dwagent.sh --uninstall
```
No physical access to the remote machine so…

And I remind using _sudo_ when installing.

**Comment by edgarbc** [comment]
> I have installed these virtual machine Ubuntu 18.04, Xubuntu 18.04 and screen works fine. Maybe there was a problem on agent update. Can you reinstall it?

Hi there, 

What is the best way to re-install it? Should I run the script again or there is an uninstall option?

Thanks!

**Comment by dwservice** [comment]
Hello, today we have published a new update. On some linux when dwagent load audio library the process crash. We have skip load audio on these. 
The agent updates automatically but sometime need reboot and rarely need reinstallation. (To reinstall you have to uninstall and install).

Please let me know if it works and I can close the issue.

**Comment by notAro14** [comment]
Hello, for me it works fine now. I'm on a Pop OS 20.04. Thanks.

**Comment by qskousen** [comment]
Yes, my version auto updated and is working fine now! Thank you so much!

**Comment by edgarbc** [comment]
Hi, 
In my case I was still getting the same message "No active screen has been recognized". So I restarted the machine and now I get "Error: XWayland is not supported."

I am running dwservice on:
```
Linux myserver2 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Any idea if this is related or need to do something else?

Thanks!

**Comment by edgarbc** [comment]
Update on this: I disabled Xwayland as explained [here](https://linuxconfig.org/how-to-disable-wayland-and-enable-xorg-display-server-on-ubuntu-18-04-bionic-beaver-linux) to change to Xorg and dwservice works again! 👍

**Comment by edgarbc** [comment]
But now back to the "No active screen has been recognized." message. I guess there was a recent update?

**Comment by dwservice** [comment]
@edgarbc Do you get that message when remote PC is on login manager or when linux user is logged in?

**Comment by Coeur-Noir** [comment]
![dwservice](https://user-images.githubusercontent.com/1895947/99882115-73e59980-2c1e-11eb-8f6c-33845f600d4a.png)
If I run the uninstall script to be found in `/usr/bin/dwaguninstall` remotely,

I guess I'll be immediately logged out ??? And then unable to reinstall dwagent… until I go physically to that machine - which is a bit delicate in those lockdown days.

**Comment by dwservice** [comment]
@Coeur-Noir  Yes will lost the connection. There are still problem on some Linux distros so wait before to go there. If we can to reproduce the issue, maybe we fix it in next weeks. Anyway you can perform Agent reboot from your DWS account, I do not know if helps.

**Comment by edgarbc** [comment]
> 
> 
> @edgarbc Do you get that message when remote PC is on login manager or when linux user is logged in?

I get that error message after I press the Screen button. I never get to the login screen.

**Comment by dwservice** [comment]
@edgarbc I mean on remote machine the user is logged? or is it on login manager?

**Comment by edgarbc** [comment]
@dwservice sorry, I misunderstood. Yes, the user is logged in.

**Comment by edgarbc** [comment]
I also tested to log the user out and try to use the Screen button. In this case, I get to the Ubuntu login screen but after typing the username and password, I can not press Sign In or <enter> so I am stuck there...

**Comment by edgarbc** [comment]
Following up, when I log in with the Shell button, I can see that the user it is actually signed in in the previous step, even though I never passed the log in screen.

**Comment by dwservice** [comment]
@edgarbc can you try now, I have published a new update

**Comment by edgarbc** [comment]
Hi there, I rebooted and tried again with very similar results 

![image](https://user-images.githubusercontent.com/4164895/99889152-b3f15000-2c0f-11eb-860d-f3ef48e7f4ef.png)

After I press <Enter>, I get stuck in the login page but the user actually is logged on.

**Comment by dwservice** [comment]
run this commands when user is logged in and give me results:

ps -ef | grep Xorg

sudo fgconsole

I will do others checks next week.

**Comment by t8lucas** [comment]
I`m trying to remote a laptop with Manjaro installed and every time when I reboot the machine by the dwagent terminal, so, I can use it just a few minutes before the error message appears "Erro: Process not started." in the middle of my access. After that, I can`t reaccess Manjaro again. Only if, I reboot one more time but it`ll start all over again after a few minutes of use. Is there any other way to fix this problem waiting for a new update or I have to uninstall the agent and install it again to solve this problem physically?

**Comment by edgarbc** [comment]
@dwservice this is the output of ps and fgconsole as requested:

![image](https://user-images.githubusercontent.com/4164895/99910659-7ee70b00-2cac-11eb-9630-2f239f09abef.png)

Thanks!

**Comment by t8lucas** [comment]
I just reinstalled the agent from Manjaro but still get the error message. Right now I'm using Windows remotely from another Linux and everything is perfectly fine

**Comment by Coeur-Noir** [comment]
> Anyway you can perform Agent reboot from your DWS account, I do not know if helps.

Unfortunately it has not helped, nothing on screen, only « Erreur : Process not started »

Here same logs as requested, as _root_ then _$USER_ : 
```
root@REMOTE:/# ps -ef | grep dw
root       753     1  0 nov.17 ?       00:00:00 /bin/sh /usr/share/dwagent/native/dwagsvc run
root     19143   753  0 02:19 ?        00:00:01 /usr/share/dwagent/runtime/bin/dwagent agent.pyc -filelog
root     19224 19213  0 02:21 pts/0    00:00:00 grep --color=auto dw
root@REMOTE:/# ps -ef | grep xorg
root       761   732  0 nov.17 tty7    00:07:36 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
root     19229 19213  0 02:22 pts/0    00:00:00 grep --color=auto xorg
root@REMOTE:/# su myself
myself@REMOTE:/$ ps -ef | grep dw
root       753     1  0 nov.17 ?       00:00:00 /bin/sh /usr/share/dwagent/native/dwagsvc run
root     19143   753  0 02:19 ?        00:00:01 /usr/share/dwagent/runtime/bin/dwagent agent.pyc -filelog
myself  19241 19231  0 02:24 pts/0    00:00:00 grep --color=auto dw
myself@REMOTE:/$ ps -ef | grep xorg
root       761   732  0 nov.17 tty7    00:07:36 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
myself  19243 19231  0 02:24 pts/0    00:00:00 grep --color=auto xorg
myself@REMOTE:/$ sudo fgconsole
[sudo] Mot de passe de myself : 
7
myself@REMOTE:/$
```

**Comment by dwservice** [comment]
Unfortunately we can not reproduce the issue, we have installed a lot of Linux distros and it works well. It could be your local problem. We need to connect to your PC in order to understand the issue. Please send mail to DWService support if you can share your PC with us.

**Comment by Coeur-Noir** [comment]
> Unfortunately we can not reproduce the issue, we have installed a lot of Linux distros and it works well. It could be your local problem. We need to connect to your PC in order to understand the issue. Please send mail to DWService support if you can share your PC with us.

Hello, sorry for delay.

First : thank you for your offer to eventually connect to my machine. I was not expecting such a personalized support and it's very nice from you. But it's not a personal pc ( business ) so am not allowed to « share » it.

Second : I've managed to go there, locally / physically. Reinstalled and reconfigured dwagent. And… **problem solved** !

Maybe something with « auto-updating » did not work as expected ?

Again : BiG THANK YOU !

**Comment by edgarbc** [comment]
@Coeur-Noir glad you solved the problem. I will try to uninstall and install dwagent again. Is there a proper way to uninstall?

Thanks!

**Comment by Coeur-Noir** [comment]
Yes @edgarbc there is an uninstall script to be found in `/usr/share/bin` named `dwaguninstall`

Once uninstalled, go to your dwservice page, choose this recently uninstalled agent, and hit reinstall, this will generate a numeric id later needed.

Now run the dwagent install script.and use previously numeric id for connecting, not your email address.

**Comment by edgarbc** [comment]
@Coeur-Noir thank you. Unfortunately uninstalling did not work for me and on a long path out of frustration, I reinstalled linux and now dwagent works again :) 👍

**Comment by reverent911** [comment]
Hey guys , this might sound stupid but i had the same error with process not started. I downloaded the generic installer as well and made sure i have Python2.7 installed ( apt install python2 pip ) - did a reboot and could eventually login to the remote machine. I hope this helps somebody having this 'Process not started' issue.

**Comment by Coeur-Noir** [comment]
Problem is back.

Actually right after re-installing dwagent, the screen sharing is ok from machine A to machine B.

But if I reboot machine B then I get the _capture process not started_ message. Machine B is still Xubuntu 18.04 and has python 2.7 installed ( default from repositories ).
